commands:
  attendance:
    users:
      - 403185514796154880
      - 1012354951692963861
    roles: []
  content:
    users:
      - 403185514796154880
      - 1012354951692963861
    roles: []
  splitcomplate:
    users:
      - 403185514796154880
      - 1012354951692963861
    roles: []
