commands:
  attendance:
    users:
      - 1012354951692963861
    roles:
      - 1394773462261956789
  content:
    users:
      - 1012354951692963861
    roles:
      - 1394773462261956789
  splitcomplate:
    users:
      - 1012354951692963861
    roles:
      - 1394773462261956789
